### ISSUE TITLE
Initial issues

### ISSUE THREAD

**Issue by Commifreak** [Esinko/xibo-client-docker#1]
I move our discussion to here :)

With latest repo, I only got this far:

```
docker run -it   --hostname="$(hostname)"   --env="DISPLAY"   --volume="${XAUTHORITY:-${HOME}/.Xauthority}:/root/.Xauthority:ro"   --volume="/tmp/.X11-unix:/tmp/.X11-unix:ro"    --name="xibo-docker" esinko/xibo-client-docker
 -> Running one-time WINE configuration update ...
    Done.
 -> Running the Player Installer program ...
    Installer exited with code 67
    Generic installation failure.
```

Yes, I omitted the xibo-volume, as I dont need it now.

I edited the entrypoint to be more verbose:

```
02c8:warn:module:find_builtin_dll cannot find builtin library for L"\\??\\C:\\users\\root\\Temp\\msi2036.tmp"
01d0:warn:win:SetWindowTextW setting text L"Verifying prerequisites" of other process window 00000000 should not use SendMessage
01a8:err:msi:custom_get_thread_return invalid Return Code 2
01a8:err:msi:ITERATE_Actions Execution halted, action L"AI_VerifyPrereq" returned 1603
01a8:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
01a8:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
01a8:err:msi:ITERATE_Actions Execution halted, action L"ExecuteAction" returned 1603
01a8:warn:win:SetWindowTextW setting text L"" of other process window 00000000 should not use SendMessage
01a8:warn:win:SetWindowTextW setting text L"Dialog created" of other process window 00000000 should not use SendMessage
01a8:warn:seh:dispatch_exception EXCEPTION_ACCESS_VIOLATION exception (code=c0000005) raised
01a8:warn:seh:dispatch_exception EXCEPTION_ACCESS_VIOLATION exception (code=c0000005) raised
01a8:err:msi:dialog_run_message_loop Failed to create dialog L"FatalError"
01a8:warn:msi:MSI_InstallPackage installation failed, running rollback script
01a8:warn:seh:dispatch_exception EXCEPTION_ACCESS_VIOLATION exception (code=c0000005) raised
01c0:warn:rpc:RPCRT4_default_receive_fragment Short read of header, -1 bytes
01c0:warn:rpc:RPCRT4_io_thread receive failed with error 6be
    Installer exited with code 67
    Generic installation failure.
```

If I leave a bash here and execute the exact same wine command one more time:

```
Authorization required, but no authorization protocol specified
```

And with `warn+all`:

```
01fc:warn:rpc:process_request_packet interface {367abb81-9844-35f1-ad32-98f038001003} no longer registered, returning fault packet
0204:warn:rpc:process_request_packet interface {367abb81-9844-35f1-ad32-98f038001003} no longer registered, returning fault packet
0208:warn:rpc:process_request_packet interface {367abb81-9844-35f1-ad32-98f038001003} no longer registered, returning fault packet
0204:warn:rpc:RPCRT4_SendWithAuth rpcrt4_conn_write failed (auth)
01fc:warn:rpc:RPCRT4_SendWithAuth rpcrt4_conn_write failed (auth)
0208:warn:rpc:RPCRT4_SendWithAuth rpcrt4_conn_write failed (auth)
```

(Which is interesting, because inside previous repo version I got the Installer opening by execute the wine command twice...)

**Comment by Esinko** [comment]
> I move our discussion to here :)
> 
> With latest repo, I only got this far:
> 
> ```
> docker run -it   --hostname="$(hostname)"   --env="DISPLAY"   --volume="${XAUTHORITY:-${HOME}/.Xauthority}:/root/.Xauthority:ro"   --volume="/tmp/.X11-unix:/tmp/.X11-unix:ro"    --name="xibo-docker" esinko/xibo-client-docker
>  -> Running one-time WINE configuration update ...
>     Done.
>  -> Running the Player Installer program ...
>     Installer exited with code 67
>     Generic installation failure.
> ```
> 
> Yes, I omitted the xibo-volume, as I dont need it now.
> 
> I edited the entrypoint to be more verbose:
> 
> ```
> 02c8:warn:module:find_builtin_dll cannot find builtin library for L"\\??\\C:\\users\\root\\Temp\\msi2036.tmp"
> 01d0:warn:win:SetWindowTextW setting text L"Verifying prerequisites" of other process window 00000000 should not use SendMessage
> 01a8:err:msi:custom_get_thread_return invalid Return Code 2
> 01a8:err:msi:ITERATE_Actions Execution halted, action L"AI_VerifyPrereq" returned 1603
> 01a8:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
> 01a8:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
> 01a8:err:msi:ITERATE_Actions Execution halted, action L"ExecuteAction" returned 1603
> 01a8:warn:win:SetWindowTextW setting text L"" of other process window 00000000 should not use SendMessage
> 01a8:warn:win:SetWindowTextW setting text L"Dialog created" of other process window 00000000 should not use SendMessage
> 01a8:warn:seh:dispatch_exception EXCEPTION_ACCESS_VIOLATION exception (code=c0000005) raised
> 01a8:warn:seh:dispatch_exception EXCEPTION_ACCESS_VIOLATION exception (code=c0000005) raised
> 01a8:err:msi:dialog_run_message_loop Failed to create dialog L"FatalError"
> 01a8:warn:msi:MSI_InstallPackage installation failed, running rollback script
> 01a8:warn:seh:dispatch_exception EXCEPTION_ACCESS_VIOLATION exception (code=c0000005) raised
> 01c0:warn:rpc:RPCRT4_default_receive_fragment Short read of header, -1 bytes
> 01c0:warn:rpc:RPCRT4_io_thread receive failed with error 6be
>     Installer exited with code 67
>     Generic installation failure.
> ```
> 
> If I leave a bash here and execute the exact same wine command one more time:
> 
> ```
> Authorization required, but no authorization protocol specified
> ```
> 
> And with `warn+all`:
> 
> ```
> 01fc:warn:rpc:process_request_packet interface {367abb81-9844-35f1-ad32-98f038001003} no longer registered, returning fault packet
> 0204:warn:rpc:process_request_packet interface {367abb81-9844-35f1-ad32-98f038001003} no longer registered, returning fault packet
> 0208:warn:rpc:process_request_packet interface {367abb81-9844-35f1-ad32-98f038001003} no longer registered, returning fault packet
> 0204:warn:rpc:RPCRT4_SendWithAuth rpcrt4_conn_write failed (auth)
> 01fc:warn:rpc:RPCRT4_SendWithAuth rpcrt4_conn_write failed (auth)
> 0208:warn:rpc:RPCRT4_SendWithAuth rpcrt4_conn_write failed (auth)
> ```
> 
> (Which is interesting, because inside previous repo version I got the Installer opening by execute the wine command twice...)

The volume is required! That's where the player is installed.

**Comment by Commifreak** [comment]
I think its irrelevant, because the path still exists inside the container - its just not mapped to the host. I tried it anyway. I disacrded the WINEDEBUG to get rid of the warnings, thats the result:

```
wine ./xibo-client-v3-R301.1-win32-x86.msi 
Authorization required, but no authorization protocol specified
0050:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0050:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
0050:err:systray:initialize_systray Could not create tray window
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0108:fixme:file:NtLockFile I/O completion on lock not implemented yet
0108:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0108:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0108:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
0108:err:msi:dialog_run_message_loop Failed to create dialog L"PrepareDlg"
0108:err:msi:dialog_run_message_loop Failed to create dialog L"WelcomeDlg"
0108:err:msi:dialog_run_message_loop Failed to create dialog L"ProgressDlg"
01b8:fixme:heap:RtlSetHeapInformation handle 00000000, info_class 1, info 00000000, size 0 stub!
01b8:fixme:advapi:DecryptFileW (L"C:\\windows\\Temp\\{CC13AB62-F7CF-4784-90AF-57A25DB8016A}\\", 00000000): stub
01c4:fixme:heap:RtlSetHeapInformation handle 00000000, info_class 1, info 00000000, size 0 stub!
01c4:fixme:advapi:DecryptFileW (L"C:\\windows\\Temp\\{17191109-EC73-4963-B7F9-0028394AC77D}\\", 00000000): stub
01cc:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
01cc:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
01c4:fixme:ver:GetCurrentPackageId (0057FE94 00000000): stub
01b8:fixme:ver:GetCurrentPackageId (0057FE94 00000000): stub
0108:err:msi:custom_get_thread_return invalid Return Code 2
0108:err:msi:ITERATE_Actions Execution halted, action L"AI_VerifyPrereq" returned 1603
0108:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0108:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0108:err:msi:ITERATE_Actions Execution halted, action L"ExecuteAction" returned 1603
0108:err:msi:dialog_run_message_loop Failed to create dialog L"FatalError"
```

=>

```
01cc:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
01cc:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
```

Thants interesting... So I did a reboot of the system:
```
01a8:warn:win:SetWindowTextW setting text L"Dialog created" of other process window 00000000 should not use SendMessage
01a8:warn:seh:dispatch_exception EXCEPTION_ACCESS_VIOLATION exception (code=c0000005) raised
01a8:warn:seh:dispatch_exception EXCEPTION_ACCESS_VIOLATION exception (code=c0000005) raised
01a8:err:msi:dialog_run_message_loop Failed to create dialog L"FatalError"
01a8:warn:msi:MSI_InstallPackage installation failed, running rollback script
01a8:warn:seh:dispatch_exception EXCEPTION_ACCESS_VIOLATION exception (code=c0000005) raised
01c0:warn:rpc:RPCRT4_default_receive_fragment Short read of header, -1 bytes
01c0:warn:rpc:RPCRT4_io_thread receive failed with error 6be
    Installer exited with code 67
    Generic installation failure.
```

Same error, now it cant connect to X? Hmm..

The Xauthority is `/run/user/1000/.mutter-Xwaylandauth.IXX191` and DISPLAY also exists inside container (`:0`)

**Comment by Esinko** [comment]
I've never seen that "Authorization required..." message before. Could you make sure your XServer is accepting connections? Maybe run `xhost +`?

**Comment by Esinko** [comment]
And in terms of the volume, when the container is removed or rebuilt, the installation and configs will be destroyed. That's why I'm using a volume.

**Comment by Commifreak** [comment]
> I've never seen that "Authorization required..." message before. Could you make sure your XServer is accepting connections? Maybe run `xhost +`?

Me neither. I got it working one time. Using Ubuntu 22.04 Desktop.



> And in terms of the volume, when the container is removed or rebuilt, the installation and configs will be destroyed. That's why I'm using a volume.

Thats true.

**Comment by Commifreak** [comment]
I played a bit and I could run the Xibo installer. Unfortunately, msiexec always stops responding during installation and the hosts X11 is crashing. Ubuntu shows the login screen then and terminates the session.

**Comment by Esinko** [comment]
> I played a bit and I could run the Xibo installer. Unfortunately, msiexec always stops responding during installation and the hosts X11 is crashing. Ubuntu shows the login screen then and terminates the session.

That sounds like an issue with your X11 installation. I'd make sure it's up to date. Anyhow, I've gotten better results without msiexec. I see no good reasons to use it as the parameters that it provides (for example quiet install) do not seem to work, even though the work on Windows.

EDIT: Maybe consider checking X11's logs?

**Comment by Commifreak** [comment]
I switched from docker to a native wine installation, which succeeded so far. Yes, the newest player just crashes with ` DiscardVirtualMemory unimplemented` crash, but the 301 is working!

Maybe Xibo just have to make it a bit mor wine compatible. Since Xibo is the only thing on my machine, I believe I go with a native setup for now.
